---
- name: second ansible script
  hosts: localhost
  vars:
    - username: ubuntu
    - home: /home/ubuntu
  tasks:
    - name: print variables
      debug:
        msg: "Username: {{ username }}, Home location: {{ home }}"
