---
- hosts: localhost
  become: yes
  vars:
    page_title: My Landing Page
    page_description: This is my landing page description.
  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: latest

    - name: Apply Page Template
      template:
        src: /home/ubuntu/ashish/landingpage.html.j2
        dest: /var/www/html/index.apache3.html
